runtime: python37
entrypoint: gunicorn -b :$PORT app:flask_app
env: flex

runtime_config:
    python_version: 3
env_variables:
    mapboxkey: pk.eyJ1IjoibW9jYWlybyIsImEiOiJjanpsbHJ6cW4weDA3M25wcDhoZHJla201In0.ufg3StHaa-QJCariH4aVZA
